server:
  port: 8080

security:
  accesskey: hihi
  refreshkey: hoho

mysql:
  username: root
  password: 
  dbname: my_shop
  host: localhost
  port: 3306

mongodb:
  uri: mongodb://localhost:27017/myshop

