server:
  port: 8080

security:
  accesskey: hihi
  refreshkey: hoho

mysql:
  username: root
  password: 
  dbname: my_shop
  host: localhost
  port: 3306

mongodb:
  uri: mongodb://localhost:27017/myshop

logger:
  loglevel: debug
  filename: "./storages/logs/dev.001.log"
  maxsize: 500
  maxbackups: 3
  maxage: 28
  compress: true
